using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RestApiServices.FakeData
{
    public class BookTitles
    {

        public static string[] bookNames = new string[]
        {
            "The Whispering Shadows",
            "Echoes of Eternity",
            "The Lost Chronicles",
            "Beneath the Crimson Sky",
            "The Midnight Heirloom",
            "Dance of the Forgotten",
            "The Secret of Silverwood",
            "The Obsidian Key",
            "The Enchanted Harp",
            "The Twilight Prophecy",
            "The Silent Melody",
            "The Cursed Crown",
            "The Last Phoenix",
            "The Hidden Fortress",
            "The Mystic's Journey",
            "The Golden Eclipse",
            "The Phantom's Mask",
            "The Eternal Hourglass",
            "The Frozen Rose",
            "The Firebird's Lament",
            "The Shadow of Thorns",
            "The Forgotten Realm",
            "The Guardian's Oath",
            "The Veil of Secrets",
            "The Jade Amulet",
            "The Crystal Path",
            "The Serpent's Whisper",
            "The Fallen Star",
            "The Oracle's Gift",
            "The Lost Kingdom",
            "The Moonlit Garden",
            "The Iron Labyrinth",
            "The Sapphire Crown",
            "The Darkened Veil",
            "The Ghost of Everwood",
            "The Wishing Tree",
            "The Dragon's Heart",
            "The Shattered Mirror",
            "The Ember's Light",
            "The Thorned Crown",
            "The Wandering Bard",
            "The Emerald Quest",
            "The Gilded Cage",
            "The Sorcerer's Pact",
            "The Midnight Talisman",
            "The Blood Moon Rises",
            "The Ivory Tower",
            "The Forbidden Grimoire",
            "The Hidden Oasis",
            "The Celestial Orb",
            "The Crimson Tide",
            "The Shadow's Edge",
            "The Wand of Destiny",
            "The Lost Heir",
            "The Phoenix's Tear",
            "The Sapphire Isle",
            "The Silver Thread",
            "The Whispering Forest",
            "The Moonstone Blade",
            "The Abyssal Gate",
            "The Sorceress' Curse",
            "The Pirate King's Treasure",
            "The Golden Phoenix",
            "The Fabled Lantern",
            "The Mystic's Portal",
            "The Darkened Flame",
            "The Alchemist's Secret",
            "The Frostbound Tome",
            "The Shadow Weaver",
            "The Enchanted Seas",
            "The Warrior's Heart",
            "The Celestial Prophecy",
            "The Sapphire Dagger",
            "The Shattered Star",
            "The Dragon's Eye",
            "The Serpent's Fang",
            "The Eternal Flame",
            "The Nightfall Chronicles",
            "The Ghost of Winterfell",
            "The Forbidden Labyrinth",
            "The Mirror's Curse",
            "The Crown of Shadows",
            "The Lost Temple",
            "The Phantom's Curse",
            "The Enchanter's Ring",
            "The Celestial Sword",
            "The Secret of Avalon",
            "The Iron Codex",
            "The Silver Dawn",
            "The Ruby Key",
            "The Wanderer's Tale",
            "The Shadow of the Phoenix",
            "The Sorceress' Tower",
            "The Mystic's Legacy",
            "The Crimson Amulet",
            "The Emerald Flame",
            "The Moonlit Shadow",
            "The Obsidian Crown",
            "The Hidden Prophecy",
            "The Twilight Harbinger"
        };

    }
}
